name: silla_studio
description: A new Flutter project.
publish_to: "none" 
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  webview_flutter: ^3.0.0
  freezed: ^1.1.1
  bloc: ^8.0.2
  provider: ^6.0.2
  hive: ^2.0.5
  freezed_annotation: ^1.1.0
  flutter_bloc: ^8.0.1
  path_provider: ^2.0.8
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.7
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  hive_generator: ^1.1.2
  build_runner: ^2.1.7
  flutter_native_splash: ^2.0.2


flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: GorditaFont
      fonts:
        - asset: assets/fonts/GorditaFont/Bold.otf
          weight: 600
        - asset: assets/fonts/GorditaFont/Medium.otf
          weight: 500
        - asset: assets/fonts/GorditaFont/Regular.otf
          weight: 400

    - family: ArminSoft
      fonts:
        - asset: assets/fonts/ArminSoft/regular.ttf
          weight: 400
        - asset: assets/fonts/ArminSoft/medium.ttf
          weight: 500
        - asset: assets/fonts/ArminSoft/bold.ttf
          weight: 600
    - family: Antipasto
      fonts:
        - asset: assets/fonts/Antipasto/Medium.ttf

          