name: silla_studio
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  webview_flutter: ^3.0.0
  freezed: ^1.1.1
  bloc: ^8.0.2
  provider: ^6.0.2
  freezed_annotation: ^1.1.0
  flutter_bloc: ^8.0.1
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.7
  http: ^0.13.4
  hive: ^2.0.5
  path_provider: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  flutter_native_splash: ^2.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: ZenKaku
      fonts:
        - asset: assets/fonts/zenkaku/regular.ttf
          weight: 400
        - asset: assets/fonts/zenkaku/medium.ttf
          weight: 500
        - asset: assets/fonts/zenkaku/bold.ttf   
          weight: 600                   