name: silla_studio
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.2
  eva_icons_flutter: ^3.1.0
  firebase_auth: ^3.3.7
  firebase_core: ^1.12.0
  flutter:
    sdk: flutter
  flutter_html: ^2.2.1
  flutter_riverpod: ^1.0.3
  font_awesome_flutter: ^10.1.0
  freezed_annotation: ^1.1.0
  hive: ^2.0.5
  http: ^0.13.4
  lottie: ^1.3.0
  path_provider: ^2.0.9
  video_player: ^2.3.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.0.2
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: hibana
      fonts:
        - asset: assets/fonts/hibana.otf

    - family: stratos
      fonts:
        - asset: assets/fonts/stratos.ttf